version: '3'
services:
    mqtt:
      container_name: mqtt
      image: eclipse-mosquitto
      restart: always
      network_mode: host
    homeassistant:
      container_name: home-assistant
      image: homeassistant/home-assistant
      volumes:
        - .:/config
        - /etc/localtime:/etc/localtime:ro
      restart: always
      network_mode: host
    esphome:
      container_name: esphome
      image: esphome/esphome
      volumes:
        - ./esphome:/config
        - ./secrets.yaml:/config/secrets.yaml:ro
        - /etc/localtime:/etc/localtime:ro
      restart: always
      network_mode: host
