esphome:
  name: $devicename
  platform: ESP8266
  board: esp8285

<<: !include ../common/common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      inverted: True
    name: "${upper_devicename} Power Button"
    on_press:
      - switch.toggle: relay

status_led:
    id: status
    pin:
      number: GPIO13
      inverted: True

switch:
  - platform: gpio
    id: led
    pin: GPIO1

  - platform: gpio
    name: "${upper_devicename} Smart Plug"
    pin: GPIO14
    id: relay
    on_turn_on:
      - switch.turn_on: led
    on_turn_off:
      - switch.turn_off: led

sensor:
  - !include ../common/sensors/wifi.yaml
  - !include ../common/sensors/uptime.yaml
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: 0.00221
    voltage_divider: 871
    current:
      name: "${upper_devicename} Smart Plug current"
      unit_of_measurement: A
    voltage:
      name: "${upper_devicename} Smart Plug Voltage"
      unit_of_measurement: V
    power:
      name: "${upper_devicename} Smart Plug Wattage"
      unit_of_measurement: W
      id: "energy_temp_Wattage"
    change_mode_every: 8
    update_interval: 10s
